### ISSUE TITLE
Crear Menú de Solapas

### ISSUE THREAD

**Issue by nicolascoco85** [xpitr256/patena-front-end#23]
![image](https://user-images.githubusercontent.com/7545477/60403507-ad72bc00-9b74-11e9-82c5-f797349ceca7.png)

**Comment by nicolascoco85** [comment]
Indicar que en solapa se esta trabajando vigente distinguiéndola con un formato distinto a las otras inactivas. Mostrando el contenido que corresponda para dicha solapa activa

**Comment by xpitr256** [comment]
Done!
