### ISSUE TITLE
Crear la pantalla "HOME"

### ISSUE THREAD

**Issue by nicolascoco85** [xpitr256/patena-front-end#4]
- [x] Titulo de bienvenida

- [x] Texto descriptivo general acerca de la aplicación y sus usos

**Comment by nicolascoco85** [comment]
![image](https://user-images.githubusercontent.com/7545477/60402915-5963d980-9b6c-11e9-9249-fbc660bc0201.png)

**Comment by xpitr256** [comment]
Do it inside HomeBody component.

**Comment by nicolascoco85** [comment]
add description welcome msg
